/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeReadOptions {
  readAhead?: number
  cacheBytes?: number
}
export interface NativePixelComponent {
  code: number
  depth: number
}
export interface NativeTimecode {
  hour: number
  minute: number
  second: number
  frame: number
  dropFrame: boolean
}
export interface NativeTrack {
  index: number
  kind: string
  essenceType: string
  essenceContainerUl: Buffer
  codingUl?: Buffer
  descriptor: number
  storedWidth?: number
  storedHeight?: number
  displayWidth?: number
  displayHeight?: number
  componentDepth?: number
  horizSubsampling?: number
  vertSubsampling?: number
  frameLayout?: number
  aspectRatioNum?: number
  aspectRatioDen?: number
  videoLineMap?: Array<number>
  pixelLayout: Array<NativePixelComponent>
  colorPrimaries?: Buffer
  transferCharacteristic?: Buffer
  codingEquations?: Buffer
  samplingRate?: number
  channelCount?: number
  quantizationBits?: number
  editRateNum: number
  editRateDen: number
  duration: number
}
export interface NativeFrame {
  data: Buffer
  elementKey: Buffer
  filePosition: number
  klSize: number
  position: number
  trackIndex: number
}
export interface NativeXmlMetadata {
  data: Buffer
  schemeId?: Buffer
  language?: string
  namespace?: string
  mimeType?: string
  isXml: boolean
}
export interface NativePackage {
  frames: Array<NativeFrame>
}
export interface NativeClipInfo {
  editRateNum: number
  editRateDen: number
  duration: number
  tracks: Array<NativeTrack>
  startTimecode?: NativeTimecode
}
export declare function openMxfFromBuffer(data: Buffer, options?: NativeReadOptions | undefined | null): Promise<NativeClip>
export declare function openMxfFromPath(path: string, options?: NativeReadOptions | undefined | null): Promise<NativeClip>
export interface NativeTrackSpec {
  essenceType: number
  samplingRate?: number
  channelCount?: number
  quantizationBits?: number
  storedWidth?: number
  storedHeight?: number
  essenceContainerUl?: Buffer
  codingUl?: Buffer
  elementType?: number
  elementLlen?: number
  temporalReordering?: boolean
  descriptor?: number
  componentDepth?: number
  horizSubsampling?: number
  vertSubsampling?: number
  frameLayout?: number
  aspectRatioNum?: number
  aspectRatioDen?: number
  videoLineMap?: Array<number>
  pixelLayout?: Array<NativePixelComponent>
  colorPrimaries?: Buffer
  transferCharacteristic?: Buffer
  codingEquations?: Buffer
}
export interface NativeClipSpec {
  editRateNum: number
  editRateDen: number
  flavour?: number
  duration?: number
  tracks: Array<NativeTrackSpec>
  xml?: Array<NativeXmlMetadata>
  startTimecode?: NativeTimecode
  timecodeTrack?: boolean
  systemItem?: boolean
  identity?: NativeIdentity
}
export interface NativeIdentity {
  companyName?: string
  productName?: string
  versionString?: string
  productVersion?: Array<number>
  productUid?: Buffer
  creationDate?: Array<number>
  generationUid?: Buffer
  materialPackageUid?: Buffer
  fileSourcePackageUid?: Buffer
}
export declare function writeMxfToPath(path: string, spec: NativeClipSpec): Promise<NativeWriter>
export declare class NativeClip {
  info(): Promise<NativeClipInfo>
  select(indexes: Array<number>): Promise<void>
  seek(position: number): Promise<void>
  read(count: number): Promise<Array<NativePackage>>
  xml(): Promise<Array<NativeXmlMetadata>>
  close(): Promise<void>
}
export declare class NativeWriter {
  write(trackIndex: number, data: Buffer): Promise<void>
  finish(): Promise<void>
  close(): Promise<void>
}
