[package]
name = "mxfuse_node_bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mxfuse = { path = "../rust-mxfuse" }
napi = { version = "2", default-features = false, features = ["napi4", "tokio_rt"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
