[package]
name = "mxfuse_python_bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "mxfuse_python_bindings"
crate-type = ["cdylib"]

[dependencies]
mxfuse = { path = "../rust-mxfuse" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310"] }
