[package]
name = "mxfuse"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Read and write MXF files through a statically linked bmx core"
readme = "../../README.md"
exclude = ["../../vendor/bmx/apps", "../../vendor/bmx/tools", "../../vendor/bmx/meta"]

[lib]
crate-type = ["rlib"]

[dependencies]
mxfuse-sys = { path = "../mxfuse-sys", version = "0.1.0" }
